In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [4]:
a = np.arange(5)

print(a < 3)

[ True  True  True False False]


In [5]:
import pandas as pd

certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned)

Tom      8
Kris     2
Ahmad    5
Beau     6
dtype: int64


In [6]:
import pandas as pd

certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned[certificates_earned > 5])

Tom     8
Beau    6
dtype: int64


In [7]:
certificates_earned['Certificates per month'] = round(
    certificates_earned['Certificates'] /
    certificates_earned['Time (in months)'], 2
)

KeyError: 'Certificates'

In [8]:
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


In [9]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Replace the element at the second row (index 1) and third column (index 2) with 20
a[1, 2] = 20

print(a)

[[ 1  2  3  4  5]
 [ 6  7 20  9 10]]


In [10]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Replace the element at the second row (index 1) and third column (index 2) with 20
 
a[:, 2] = 20

print(a)

[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]


In [11]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Replace the element at the second row (index 1) and third column (index 2) with 20
 
a[2, :] = 20

print(a)

IndexError: index 2 is out of bounds for axis 0 with size 2